language: python
dist: xenial
python:
  - 2.7
  - 3.7
install:
  - pip install -U pip
  - pip install -U flake8
  - pip install -r requirements/requirements.txt
  - pip install -r requirements/requirements-ci.txt
script:
  - flake8 --statistics --count
  - coverage run test_comtrade.py
after_sucess:
- codecov

